### ISSUE TITLE
Update connection to use utf8mb4

### ISSUE THREAD

**Issue by zpchavez** [synapsestudios/synapse-base#157]
## Update connection to use utf8mb4

Additionally, point to cookbooks version that sets default DB charset to utf8mb4 (https://github.com/synapsestudios/cookbook-template/issues/13)

### Acceptance Criteria
1. {{list ACs here}}

### Tasks
- {{list developer tasks here}}

### Additional Notes
- {{list additional notes here, remove if not applicable}}

**Comment by bobeagan** [comment]
:o:

**Comment by zpchavez** [comment]
Actually, this is a template issue :boom:
