### ISSUE TITLE
FinderTrait performs table prefixing on findById() calls automatically

### ISSUE THREAD

**Issue by nearengine** [synapsestudios/synapse-base#163]
### Acceptance Criteria
1. Tests all pass
1. Doesn't break backwards compatibility
1. No column name conflicts when using FinderTrait after JOINing two tables with `id` columns.

### Additional Notes
When using a JOIN on two tables that have `id` columns, using `findById` can cause errors when trying to look up records by ID. This can be fixed by overriding `findById` and specifying the table prefix manually. However, since the mapper is aware of the table name already, I don't see a reason it can't add this to the queries automatically. It shouldn't break any existing queries, and it may prevent unexpected behavior.

**Comment by zpchavez** [comment]
Duplicates #125?

**Comment by nearengine** [comment]
:boom: Duplicate
