### ISSUE TITLE
V2: Remove deprecated features

### ISSUE THREAD

**Issue by zpchavez** [synapsestudios/synapse-base#173]
### Acceptance Criteria
1. Deprecated features removed

### Tasks
- Remove createdTimestampColumn and updatedTimestampColumn.

### Additional Notes
- {{list additional notes here, remove if not applicable}}

**Comment by paulstatezny** [comment]
:one: :arrow_down:

**Comment by zpchavez** [comment]
:sunny: :zero: :arrow_down:

**Comment by paulstatezny** [comment]
:one:

**Comment by paulstatezny** [comment]
:boom: We decided not to do this yet to maintain BC with old projects.
