### ISSUE TITLE
Stop Doing SELECT Queries Twice

### ISSUE THREAD

**Issue by paulstatezny** [synapsestudios/synapse-base#187]
### Acceptance Criteria
1. The FinderTrait is able to get the total result count of a query without re-running it.

### Tasks
- Figure out a way to do this.

### Additional Notes
- Look at `FinderTrait::getQueryResultCount`. It literally does the SELECT... and then does a separate `SELECT count(*)`. This is way deoptimized.

**Comment by paulstatezny** [comment]
:snowflake: :arrow_up:

**Comment by bobeagan** [comment]
:o:

**Comment by zpchavez** [comment]
http://stackoverflow.com/questions/186588/which-is-fastest-select-sql-calc-found-rows-from-table-or-select-count

> Many of the comments to the post seem to say that SQL_CALC_FOUND_ROWS is almost always slower - sometimes up to 10x slower - than running two queries.

**Comment by paulstatezny** [comment]
I guess we're already doing the best practice.

We can open this up if we decide. :boom:
