### ISSUE TITLE
Add File-based functionality (service & controllers)

### ISSUE THREAD

**Issue by baohx2000** [synapsestudios/synapse-base#191]
Applications need a way to upload, save, and retrieve files

### Acceptance Criteria
1. Services exist to save to either S3 or local filesystem based on configuration
1. Unit tested
1. Optional integration unit tests
1. Abstract controller
1. Abstract mapper (concrete mapper & controllers will be created for specific file types)
1. Schema stub or cli command to create table

### Tasks
- {{list developer tasks here}}

### Additional Notes
- {{list additional notes here, remove if not applicable}}

**Comment by tdboone** [comment]
:o:

**Comment by baohx2000** [comment]
:3:

**Comment by baohx2000** [comment]
:three:

**Comment by paulstatezny** [comment]
I'm not sure I understand the vision here.

Questions:

1. Is there anything really to abstract? The AWS SDK should make it simple to upload to S3.
1. What do these abstract controllers and mappers do? Is the point to have a `files` table that keeps track of them?

**Comment by baohx2000** [comment]
standard mapper, controller, and service handler.  yes, there will be a files table

**Comment by paulstatezny** [comment]
I'm not sure this will be used on a majority of projects. So that leads me to the question, is it really appropriate for base?

**Comment by baohx2000** [comment]
Should this be a separate composer package / repo then?

**Comment by paulstatezny** [comment]
That would make sense to me. I wouldn't actually put it on Packagist because it won't really be that reusable apart from our stack / project template. But it could still be included via composer.

**Comment by baohx2000** [comment]
Agree

**Comment by baohx2000** [comment]
:boom:
