### ISSUE TITLE
v2: Move Mapper Traits Into AbstractMapper

### ISSUE THREAD

**Issue by paulstatezny** [synapsestudios/synapse-base#40]
### Acceptance Criteria
1. All normal mapper traits are moved into AbstractMapper.
1. Pivot traits are moved into AbstractPivotMapper, which is a child of AbstractMapper.

### Tasks
- Move trait code into AbstractMapper.
- Move pivot traits into AbstractPivotMapper but find a better name for it. (Tables without an auto-incrementing ID aren't always pivot tables.)
- Remove `use [trait]` code from mappers

### Additional Notes
- The original idea for these traits was this: By segmenting them into separate traits, it makes it more difficult to "accidentally" perform an insert/update/delete on tables that our app should never insert/update/delete. The reality: If a developer is going to do something stupid, segmenting the mapper isn't going to stop them.
- This is a **Backwards Compatibility Breaking Change**. When it is released into `master`, major version should be bumped to **2**. Dependents must remove `use [mapper trait]` code from mappers.

**Comment by paulstatezny** [comment]
:one:

**Comment by paulstatezny** [comment]
:o:

**Comment by paulstatezny** [comment]
:two:

**Comment by paulstatezny** [comment]
:two:

**Comment by paulstatezny** [comment]
:arrow_down: :snowflake:

**Comment by zpchavez** [comment]
These traits have kind of grown on me.

**Comment by paulstatezny** [comment]
@zpchavez what are the benefits of keeping them separate from your perspective?

**Comment by paulstatezny** [comment]
:boom:
